name:                ssb-client-hs
version:             0.1.0.0
github:              "githubuser/ssb-client-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ssb-client-hs#readme>

dependencies:
- base              >= 4.7     && < 5

- memory            >= 0.14    && < 1
- text              >= 1.2.3.0 && < 2
- time              >= 1.8.0   && < 2
- utf8-string       >= 1.0.1.1 && < 2
- bytestring        >= 0.10    && < 1
- base64-bytestring >= 1.0.0.1 && < 2

# JSON
- aeson             >= 1.2.4.0 && < 2
- aeson-pretty      >= 0.8.7   && < 1

# Crypto
- cryptonite        >= 0.25    && < 1

# Networking
- connection        >= 0.2.8   && < 1
- connection-pool   >= 0.2.2   && < 1

# ORM
- persistent

# Test
- QuickCheck        >= 2.10.1  && < 3


library:
  source-dirs: src

executables:
  ssb-client-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ssb-client-hs

tests:
  ssb-client-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ssb-client-hs

    - hspec      >= 2.4.8  && < 3
